### PR TITLE
Update the documentation by adding the logo

### PR DESCRIPTION
**Pull request by NeKo2903**

### CODE REVIEW

**Review by pawelmagnu — APPROVED** [review]
looks good to me

**Comment by slayoo** [comment]
Thanks!
Should we add it also to the pdoc template (https://github.com/open-atmos/PyMPDATA/blob/main/pdoc_templates/index.html.jinja2)?

**Comment by pawelmagnu** [comment]
@slayoo is this what you had in mind?

**Comment by slayoo** [comment]
Yes, thanks! I guess we need to merge to check if all works OK, so let's do it!

**Pull request merged**
