### PR TITLE
introducing multi-threaded parallelism

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Review by piotrbartman — CHANGES_REQUESTED** [review]
`test_traversals()` is ok but I still have a few remarks:

Default value for `jit_flags={}`, `n_threads=1` in `Traversals`? And maybe for `halo`. (And maybe not only in `Traversals`.) Imo, if only the default variable does not silently change the program results, it should be specified.

`raise ValueError('Null function error.')` instead of returning value in `null.py`.

`irng` - a little unclear name, acceptable for local variable, but it not say what it is.

Move `_make_apply_scalar`, `_make_apply_vector`, `_make_boundary_condition` to separate files? This is in fact  static methods.

**Comment by slayoo** [comment]
> `raise ValueError('Null function error.')` instead of returning value in `null.py`.

null.py removed in https://github.com/atmos-cloud-sim-uj/MPyDATA/pull/86/commits/f05da4761f5d7378893c91dcd6ce018766a8fcbc - everything works after replacing the null formulae with ``None``s

**Comment by slayoo** [comment]
> `test_traversals()` is ok 

It should be even more OK with: https://github.com/atmos-cloud-sim-uj/MPyDATA/pull/86/commits/84d1001dde6eb9f91fdc54343928db3418956c7c :)

**Comment by slayoo** [comment]
> Move `_make_apply_scalar`, `_make_apply_vector`, `_make_boundary_condition` to separate files? This is in fact static methods.

Addressed in: https://github.com/atmos-cloud-sim-uj/MPyDATA/pull/86/commits/f105240eca69bc6720b321927a5bf416cfa08138

**Comment by slayoo** [comment]
> Default value for `jit_flags={}`, `n_threads=1` in `Traversals`? And maybe for `halo`. (And maybe not only in `Traversals`.) Imo, if only the default variable does not silently change the program results, it should be specified.

In principle, I fully agree. However, I would prefer to encourage setting it at the calling scope to reduce the risk of an unintended non-optimal performance. 

Halo does not have any sensible default value.

**Comment by piotrbartman** [comment]
> > Default value for `jit_flags={}`, `n_threads=1` in `Traversals`? And maybe for `halo`. (And maybe not only in `Traversals`.) Imo, if only the default variable does not silently change the program results, it should be specified.
> 
> In principle, I fully agree. However, I would prefer to encourage setting it at the calling scope to reduce the risk of an unintended non-optimal performance.
> 
> Halo does not have any sensible default value.

non-optimal performance is better than non-user-friendly API (like `for element in np.array(...)` in Python is non-optimal, but nice to have)

**Comment by slayoo** [comment]
> `irng` - a little unclear name, acceptable for local variable, but it not say what it is.

Addressed in: https://github.com/atmos-cloud-sim-uj/MPyDATA/pull/86/commits/cbda6406c13eeb06f73ff65c2aabdd27c22a1dcd ... but suggestions welcome how to name it better :)

**Comment by slayoo** [comment]
> non-optimal performance is better than non-user-friendly API

Indeed, but Traversals is not really part of the API - it is used internally in just one single place (+ tests) and there is no reason for exposing it to the user.

Moreover, jit_flags={} is simply not a sensible default - e.g., in test_timing_2d it results in over 7-fold longer wall times

I would even say that the Traversals class should disappear at all, but let's address it in another PR, adding an issue:https://github.com/atmos-cloud-sim-uj/MPyDATA/issues/97

**Review by piotrbartman — APPROVED** [review]

**Pull request merged**
