### PR TITLE
added more verbose explanations of solver, halo and g_factor

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by pawelmagnu** [comment]
@slayoo Could you look into this weird error with tests on windows?

**Comment by slayoo** [comment]
cannot think of any better solution than re-running the failed ones...

**Comment by pawelmagnu** [comment]
Well, that worked partially. It seems the windows examples still time out. Maybe we could re-run it again?

**Comment by slayoo** [comment]
sure (do you have the "re-run failed jobs" button visible? top right, above the logs)

**Pull request merged**
