### PR TITLE
remove nogus array flip in 2D adv-diff example + code cleanup

### PR DESCRIPTION
**Pull request by AgnieszkaZaba**

### CODE REVIEW

**Comment by pawelmagnu** [comment]
I am not sure if this is a debug leftover; when plotting images pixel 0,0 is in the top left in matplotlib, but in most visualizations, it is in the bottom left, so I guess this flip is necessary

**Comment by AgnieszkaZaba** [comment]
> I am not sure if this is a debug leftover; when plotting images pixel 0,0 is in the top left in matplotlib, but in most visualizations, it is in the bottom left, so I guess this flip is necessary

Maybe something changed because I run this notebook yesterday and saved animation was flipped (compared to initial and final plots). Could you check it?

**Comment by slayoo** [comment]
Note: `imshow` features the `origin` parameter which is set to `upper` by default, but can be changed to `lower`: https://matplotlib.org/stable/users/explain/artists/imshow_extent.html

Also, it would be best to use the `plot` function also within animation generation to ensure that the data are plotted in exactly the same way both in the plots and in the animation.

**Comment by slayoo** [comment]
@AgnieszkaZaba, @pawelmagnu, ping :) let's sort this one out!

**Comment by pawelmagnu** [comment]
I think we still need to remove the flipud statement

**Comment by AgnieszkaZaba** [comment]
> I think we still need to remove the flipud statement

Ok, we can remove flipud. But then if we set 'origin' to 'lower', we have to do the same for previous plots.

**Comment by AgnieszkaZaba** [comment]
Now it using plot function (as @slayoo suggested). 
@pawelmagnu extra parameter was added to plot function (for deciding if colorbar should be shown). Maybe there is a better way to do this?

**Review by slayoo — APPROVED** [review]

**Pull request merged**
